### ISSUE TITLE
App should launch even if no video files exist

### ISSUE THREAD

**Issue by christophergeiger3** [arBalasquide/media_server#12]
The app should still launch even if no media files exist -- also the `server started successfully` message should only deploy once the server has successfully started. After `git clone`-ing into a fresh directory this is the output:

```
Server started sucesfully. Listening on port 8080
/home/christopher/Documents/Code/media_server/gathermedia.js:24
   for (var i=0; i<items.length; i++) {
                         ^
TypeError: Cannot read property 'length' of undefined
```

**Comment by arBalasquide** [comment]
Fixed it a bit and now it starts even if theres no media found, but if theres no media folder theres still an error.

Edit: Will probably just make it so if folder is not found, then itll create it for the user.

**Comment by arBalasquide** [comment]
Added try catches to check for media folder existence and whether or not the media has actual content or not.
