### ISSUE TITLE
Add JSDoc and type checking

### ISSUE THREAD

**Issue by christophergeiger3** [arBalasquide/media_server#19]
It's kind of a cool idea to have standardized documentation for functions we write, and if we do that, we might as well go the full mile and do type checking as well: https://www.typescriptlang.org/

**Comment by arBalasquide** [comment]
@christophergeiger3 I don't think docs are completely necessary nor to do type checking. If we can manage to keep the code simple an organized, docs aren't needed besides for how to run the program.

I simply don't see why additional docs besides a README is necessary if we're following a styling guide and trying to make the code as self-explanatory as possible.

Perhaps if we are to add API capabilities to this, then I think documentation will be a good addition. But if you want, have a separate branch that implements it. Maybe I'm not seeing your view of how it can be useful.

**Comment by arBalasquide** [comment]
@christophergeiger3 don't you dare close this

**Comment by christophergeiger3** [comment]
watch me
