### ISSUE TITLE
Use the ExpressJS Framework

### ISSUE THREAD

**Issue by christophergeiger3** [arBalasquide/media_server#2]
I think we should migrate to use express, to make managing requests as painless as possible.

**Comment by arBalasquide** [comment]
Why should we use ExpressJS? What does it provide?

**Comment by christophergeiger3** [comment]
@arBalasquide Basically neaten up the way we handle different response types, and makes routing to different URLs a little simpler.

**Comment by christophergeiger3** [comment]
@arBalasquide E.g. instead of `if(request.method == 'GET' && request.url == '/') { ... }` we could do `app.get('/' (req, res) => { ... } )`

**Comment by christophergeiger3** [comment]
@arBalasquide I'm gonna create a new branch under `feature/add-express-support`. Once the changes I've made are ready, I'll create a PR, and add you as a reviewer.

**Comment by arBalasquide** [comment]
@christophergeiger3 I'm unfamiliar with that library so I do not know exactly what app.get(...) is doing. Is it simply grabbing all GET requests at '/' and setting up an anonymous function for that?

**Comment by arBalasquide** [comment]
Anyhow, read up a bit on what it does and makes things simpler. Create the new branch and re-design the onRequest function of main.js using ExpressJS and add me as reviewer.

**Comment by christophergeiger3** [comment]
@arBalasquide well if you say so
