### ISSUE TITLE
Shift towards ES6

### ISSUE THREAD

**Issue by christophergeiger3** [arBalasquide/media_server#3]
We should shift towards using a more ES6 style notation for clarity, and because it's the new standard. We could start by changing `require()`'s into `import` statements, and by using `const` instead of var, when possible.

**Comment by arBalasquide** [comment]
@christophergeiger3 Make a separate branch refactoring the code into ES6 style for me to review, learn, and merge.

**Comment by christophergeiger3** [comment]
So, #13 would be something like the first PR out of two total PRs. The next will be one actually refactoring code to use ES6 (not just adding ES6 support).

**Comment by arBalasquide** [comment]
Ok, perfect. If code is too obscure to understand just message me so we can work on it together and refactor into ES6 more coherently.
